# Generated by Django 3.0.4 on 2020-04-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='category',
        ),
    ]
