# Generated by Django 3.0.4 on 2020-04-03 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contactus',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
