# Generated by Django 3.0.4 on 2020-04-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_setting_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contactus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
