# Generated by Django 3.0.4 on 2020-04-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200406_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmassage',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10),
        ),
    ]
