# Generated by Django 3.0.4 on 2020-04-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200406_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='maps',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
