# Generated by Django 3.0.4 on 2020-04-05 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_setting_maps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='maps',
            new_name='map',
        ),
    ]
