# Generated by Django 3.0.4 on 2020-04-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200406_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='map',
            field=models.TextField(blank=True),
        ),
    ]
