# Generated by Django 3.0.4 on 2020-05-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200406_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmassage',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], max_length=10),
        ),
    ]
