# Generated by Django 3.0.4 on 2020-05-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='newsnumber',
            new_name='ordernumber',
        ),
    ]
