# Generated by Django 3.0.4 on 2020-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20200521_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmassage',
            name='message',
            field=models.CharField(max_length=250),
        ),
    ]
